export const initialFacts = [
  {
    text: "JavaScript fue creado en solo 10 días por Brendan Eich",
    source: "https://es.wikipedia.org/wiki/JavaScript",
    category: "technology",
    votesInteresting: 18,
    votesMindblowing: 12,
    votesFalse: 1,
    createdIn: 1995,
  },
  {
    text: "El primer virus informático se creó en 1986 y se llamaba Brain",
    source: "https://es.wikipedia.org/wiki/Brain_(virus_informático)",
    category: "technology",
    votesInteresting: 14,
    votesMindblowing: 9,
    votesFalse: 0,
    createdIn: 1986,
  },
  {
    text: "La miel nunca se echa a perder; los arqueólogos han encontrado miel comestible en tumbas antiguas",
    source: "https://www.nationalgeographic.com.es/",
    category: "science",
    votesInteresting: 20,
    votesMindblowing: 15,
    votesFalse: 0,
    createdIn: 2023,
  },
  {
    text: "Los plátanos son bayas, pero las fresas no lo son",
    source: "https://www.britannica.com/",
    category: "science",
    votesInteresting: 25,
    votesMindblowing: 17,
    votesFalse: 2,
    createdIn: 2023,
  },
  {
    text: "El Gran Incendio de Londres en 1666 destruyó gran parte de la ciudad, pero solo se registraron seis muertes",
    source: "https://www.britannica.com/event/Great-Fire-of-London",
    category: "history",
    votesInteresting: 16,
    votesMindblowing: 10,
    votesFalse: 0,
    createdIn: 1666,
  },
  {
    text: "Cleopatra vivió más cerca en el tiempo del alunizaje que de la construcción de la Gran Pirámide",
    source: "https://www.history.com/",
    category: "history",
    votesInteresting: 22,
    votesMindblowing: 18,
    votesFalse: 1,
    createdIn: 30,
  },
  {
    text: "Los Juegos Olímpicos fueron originalmente un festival religioso en honor a Zeus",
    source: "https://www.olympic.org/ancient-olympic-games",
    category: "sports",
    votesInteresting: 19,
    votesMindblowing: 14,
    votesFalse: 0,
    createdIn: 776,
  },
  {
    text: "El baloncesto fue inventado en 1891 por James Naismith en Springfield, Massachusetts",
    source: "https://www.history.com/topics/sports/basketball",
    category: "sports",
    votesInteresting: 21,
    votesMindblowing: 13,
    votesFalse: 0,
    createdIn: 1891,
  },
  {
    text: "La primera tarjeta de crédito moderna fue emitida por Diners Club en 1950",
    source: "https://es.wikipedia.org/wiki/Tarjeta_de_cr%C3%A9dito",
    category: "finance",
    votesInteresting: 17,
    votesMindblowing: 11,
    votesFalse: 0,
    createdIn: 1950,
  },
  {
    text: "El bitcóin fue creado en 2009 por una persona o grupo bajo el seudónimo Satoshi Nakamoto",
    source: "https://es.wikipedia.org/wiki/Bitcoin",
    category: "finance",
    votesInteresting: 23,
    votesMindblowing: 19,
    votesFalse: 1,
    createdIn: 2009,
  },
  {
    text: "El idioma más hablado del mundo es el inglés si contamos hablantes totales, pero el mandarín lidera en hablantes nativos",
    source:
      "https://es.wikipedia.org/wiki/Idiomas_por_n%C3%BAmero_de_hablantes",
    category: "society",
    votesInteresting: 21,
    votesMindblowing: 13,
    votesFalse: 0,
    createdIn: 2023,
  },
  {
    text: "Más de la mitad de la población mundial vive en áreas urbanas",
    source:
      "https://www.un.org/development/desa/es/news/population/world-urbanization-prospects.html",
    category: "society",
    votesInteresting: 18,
    votesMindblowing: 10,
    votesFalse: 0,
    createdIn: 2022,
  },
  {
    text: "La película Avatar (2009) fue la más taquillera de la historia durante casi una década",
    source: "https://es.wikipedia.org/wiki/Avatar_(pel%C3%ADcula_de_2009)",
    category: "entertainment",
    votesInteresting: 20,
    votesMindblowing: 15,
    votesFalse: 0,
    createdIn: 2009,
  },
  {
    text: "El Festival de Cannes se celebró por primera vez en 1946",
    source:
      "https://es.wikipedia.org/wiki/Festival_Internacional_de_Cine_de_Cannes",
    category: "entertainment",
    votesInteresting: 14,
    votesMindblowing: 9,
    votesFalse: 0,
    createdIn: 1946,
  },
  {
    text: "Dormir menos de seis horas por noche de forma regular aumenta el riesgo de enfermedades cardíacas",
    source: "https://www.cdc.gov/sleep/about_sleep/chronic_disease.html",
    category: "health",
    votesInteresting: 22,
    votesMindblowing: 14,
    votesFalse: 0,
    createdIn: 2023,
  },
  {
    text: "La penicilina fue descubierta accidentalmente por Alexander Fleming en 1928",
    source: "https://es.wikipedia.org/wiki/Penicilina",
    category: "health",
    votesInteresting: 25,
    votesMindblowing: 18,
    votesFalse: 0,
    createdIn: 1928,
  },
  {
    text: "El 20 de julio de 1969, el Apolo 11 logró el primer alunizaje tripulado",
    source: "https://es.wikipedia.org/wiki/Apolo_11",
    category: "news",
    votesInteresting: 26,
    votesMindblowing: 20,
    votesFalse: 0,
    createdIn: 1969,
  },
  {
    text: "La caída del Muro de Berlín en 1989 marcó el inicio del fin de la Guerra Fría",
    source: "https://es.wikipedia.org/wiki/Ca%C3%ADda_del_Muro_de_Berl%C3%ADn",
    category: "news",
    votesInteresting: 24,
    votesMindblowing: 17,
    votesFalse: 0,
    createdIn: 1989,
  },
];
